server:
  api:
    port: 8001
agent:
  type: "LANGGRAPH"
  config:
    name: "Chlo√©"
    graph_definition: "app/agent/workflow_graph.py:app"
    input_schema_definition: "invoke_request"
    checkpointer:
      type: "memory"
